phases: 
  install: 
    runtime-versions: 
      nodejs: 10 
  build: 
    commands: 
      - "echo Build started..." 
      #- "npm install gulp -g" 
      - "npm i"
      - "npm run build"
      #- "npm run upload" 
      - "echo Build completed." 
  post_build: 
    commands:
      - "echo Testing"
      - "npm run test"
  pre_build: 
    commands: 
version: 0.2